version: '3'
services:

  proxy:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    environment:
      VIRTUAL_HOST: mstdn.mikumiku.moe
      VIRTUAL_PORT: 80
    network_mode: bridge
    restart: always
    links:
      - web
      - streaming
  db:
    network_mode: bridge
    restart: always
    image: postgres:alpine
    volumes:
      - /data/mastodon/postgres:/var/lib/postgresql/data

  redis:
    network_mode: bridge
    restart: always
    image: redis:alpine
    volumes:
      - /data/mastodon/redis:/data

  web:
    network_mode: bridge
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
      - db
      - redis
    volumes:
      - /data/mastodon/public/assets:/mastodon/public/assets
      - /data/mastodon/public/packs:/mastodon/public/packs
      - /data/mastodon/public/system:/mastodon/public/system

  streaming:
    network_mode: bridge
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    links:
      - db
      - redis

  sidekiq:
    network_mode: bridge
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -q default -q pull -q push
    links:
      - db
      - redis
    volumes:
      - /data/mastodon/public/system:/mastodon/public/system
